name: Build and Push Docker Image

on:
    workflow_dispatch:
        inputs:
            image_folder:
                description: 'Folder name containing the Dockerfile'
                required: true
                default: 'blue-agent'
            version_tag:
                description: 'Version to tag the container image with'
                required: true
                default: 'latest'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
        NAMESPACE: "hayone"
    steps:
      # - name: Check out the repo
      #   uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.NAMESPACE }}/${{ github.event.inputs.image_folder }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ github.event.inputs.image_folder }}"
          # file: "./${{ github.event.inputs.image_folder }}/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.NAMESPACE }}/${{ github.event.inputs.image_folder }}:${{ github.event.inputs.version_tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/${{ env.NAMESPACE }}/${{ github.event.inputs.image_folder }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true